version: "3.6"
services:
  web:
    build: .
    container_name: investarget-mobile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
